kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-capture
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
  storageAccount: satkristest #change here storage account

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-capture
  resources:
    requests:
      storage: 200Gi
---


apiVersion: v1
kind: Pod
metadata:
     name: tcpdump
spec:
      hostPID: true
      hostNetwork: true
      securityContext:
        runAsUser: 0
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: tcpdump
        args: ["-s", "300", "-C", "2000", "-w", "/tmp/azure/node.pcap" ] #change file name here for each node put nodename.pcap instead of node.pcap
        image: docker.io/corfr/tcpdump
        resources:
          requests:
            cpu: 50m
            memory: 50M
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/tmp/azure"
            name: capture
            readOnly: false
      volumes:     
      - name: capture
        persistentVolumeClaim:
          claimName: azurefile
      nodeSelector:
            kubernetes.io/hostname : aks-agentpool-12499932-vmss000000 # change here node name

